<?php

/**
 * @file
 * Primary module hooks for Description Content Type module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_theme().
 */
function cnt_description_theme() {
  return [
    'cnt_description_in_page_navigation' => [
      'variables' => [
        'title' => 'Page Contents',
        'links' => NULL,
      ],
    ],
  ];
}
