<?php

/**
 * @file
 * Contains cnt_page.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function cnt_page_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the cnt_page module.
    case 'help.page.cnt_page':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Cnect Page') . '</p>';
      return $output;

    default:
  }
}
